package entity;
// Generated Mar 9, 2017 10:24:28 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private int masv;
     private Serializable name;
     private Double mark;
     private Serializable major;

    public Students() {
    }

	
    public Students(int masv) {
        this.masv = masv;
    }
    public Students(int masv, Serializable name, Double mark, Serializable major) {
       this.masv = masv;
       this.name = name;
       this.mark = mark;
       this.major = major;
    }
   
    public int getMasv() {
        return this.masv;
    }
    
    public void setMasv(int masv) {
        this.masv = masv;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Double getMark() {
        return this.mark;
    }
    
    public void setMark(Double mark) {
        this.mark = mark;
    }
    public Serializable getMajor() {
        return this.major;
    }
    
    public void setMajor(Serializable major) {
        this.major = major;
    }




}


